"""
Phase A contract tests for the Careers recruitment core.

Verifies spec-compliant identifier formats (§8, §55), 30-status pipeline
(§10) with history logging, job lifecycle transitions (§55), Kanban board
grouping (§12), recruitment source tracking (§44), and deadline / vacancy
gating.

Runs against the LIVE backend at REACT_APP_BACKEND_URL — these are
integration tests, not pure unit tests. Skipped if the URL is unset.
"""
import os
import re
import time
import pytest
import requests

API = (os.environ.get("REACT_APP_BACKEND_URL") or "").rstrip("/")

pytestmark = pytest.mark.skipif(not API, reason="REACT_APP_BACKEND_URL not set")


def _make_job(**overrides):
    payload = {
        "title": f"Phase A test job {int(time.time()*1000)}",
        "department": "Technology",
        "description": "Auto-generated by Phase A contract tests.",
        "vacancy_count": 2,
        "admin_id": "pytest_phaseA",
    }
    payload.update(overrides)
    r = requests.post(f"{API}/api/public/careers/jobs/create", json=payload, timeout=30)
    r.raise_for_status()
    return r.json()["job"]


def _make_resume_bytes():
    return b"%PDF-1.4\nDummy resume for pytest\n"


def _apply(job_key, email, source="Website"):
    files = {"resume": ("resume.pdf", _make_resume_bytes(), "application/pdf")}
    data = {
        "job_id": job_key,
        "name": "Phase A Applicant",
        "email": email,
        "phone": "9876500000",
        "experience_years": "1",
        "cover_letter": "",
        "linkedin": "",
        "recruitment_source": source,
    }
    return requests.post(f"{API}/api/public/careers/apply", files=files, data=data, timeout=30)


def test_meta_returns_30_statuses_and_sources():
    """Spec §10: 30 canonical statuses. §44: 10 recruitment sources."""
    r = requests.get(f"{API}/api/public/careers/meta", timeout=30)
    assert r.status_code == 200
    m = r.json()
    assert len(m["application_statuses"]) == 30
    assert len(m["recruitment_sources"]) == 10
    assert "hiring_types" in m and len(m["hiring_types"]) >= 5


def test_job_code_and_slug_and_application_id_formats():
    """Spec §8, §55 — deterministic sequential ID formats."""
    job = _make_job()
    assert re.match(r"^PR-JOB-\d{4}-\d{4}$", job["job_code"]), job["job_code"]
    assert re.match(r"^[a-z0-9-]+$", job["slug"]), job["slug"]
    assert job["job_status"] == "published"

    email = f"phaseA_ids_{int(time.time())}@test.com"
    r = _apply(job["job_id"], email)
    assert r.status_code == 200, r.text
    body = r.json()
    assert re.match(r"^PR-HR-\d{4}-\d{5}$", body["application_id"]), body["application_id"]
    assert body["job_code"] == job["job_code"]


def test_apply_by_slug_works():
    """Public-facing apply must accept slug in place of job_id."""
    job = _make_job()
    email = f"phaseA_slug_{int(time.time())}@test.com"
    r = _apply(job["slug"], email)
    assert r.status_code == 200, r.text


def test_status_transition_and_history():
    """30 canonical statuses accepted; invalid rejected; history logged."""
    job = _make_job()
    email = f"phaseA_hist_{int(time.time())}@test.com"
    app_id = _apply(job["job_id"], email).json()["application_id"]

    # 10 sequential transitions
    for status in [
        "under_screening", "shortlisted", "test_assigned", "test_completed",
        "hr_interview_scheduled", "selected", "documents_verified",
        "offer_generated", "offer_accepted", "joined",
    ]:
        r = requests.put(
            f"{API}/api/public/careers/applications/{app_id}/status",
            json={"status": status, "admin_id": "pytest", "comment": f"→{status}"},
            timeout=30,
        )
        assert r.status_code == 200, r.text
        assert r.json()["status"] == status

    # Invalid status rejected
    r = requests.put(
        f"{API}/api/public/careers/applications/{app_id}/status",
        json={"status": "bogus"},
        timeout=30,
    )
    assert r.status_code == 400
    assert "Invalid status" in r.json()["detail"]

    # History has all 10 transitions plus the initial system entry
    rl = requests.get(f"{API}/api/public/careers/applications", timeout=30).json()
    app = next(a for a in rl["applications"] if a["application_id"] == app_id)
    hist = app.get("status_history", [])
    assert len(hist) >= 11
    assert hist[0]["from"] is None and hist[0]["to"] == "application_received"
    assert hist[-1]["to"] == "joined"


def test_kanban_board_groups_by_status():
    """Spec §12: kanban returns all 30 columns with counts + card list."""
    r = requests.get(f"{API}/api/public/careers/kanban", timeout=30)
    assert r.status_code == 200
    board = r.json()["board"]
    assert len(board) == 30
    # Every column has the expected keys
    for col in board:
        assert set(col.keys()) == {"status", "label", "count", "applications"}


def test_job_lifecycle_actions_and_public_visibility():
    """Spec §55: pause hides from public listing; reopen restores."""
    job = _make_job()
    # Confirm it is publicly visible while published
    listing = requests.get(f"{API}/api/public/careers/jobs?active_only=true", timeout=30).json()["jobs"]
    assert any(j["job_id"] == job["job_id"] for j in listing)

    # Pause → gone from public listing
    r = requests.post(
        f"{API}/api/public/careers/jobs/{job['job_id']}/lifecycle",
        json={"action": "pause"}, timeout=30,
    )
    assert r.status_code == 200 and r.json()["job_status"] == "paused"
    listing = requests.get(f"{API}/api/public/careers/jobs?active_only=true", timeout=30).json()["jobs"]
    assert not any(j["job_id"] == job["job_id"] for j in listing)

    # Reopen → visible again
    r = requests.post(
        f"{API}/api/public/careers/jobs/{job['job_id']}/lifecycle",
        json={"action": "reopen"}, timeout=30,
    )
    assert r.status_code == 200 and r.json()["job_status"] == "published"

    # Invalid action → 400
    r = requests.post(
        f"{API}/api/public/careers/jobs/{job['job_id']}/lifecycle",
        json={"action": "explode"}, timeout=30,
    )
    assert r.status_code == 400


def test_paused_job_rejects_new_applications():
    job = _make_job()
    requests.post(
        f"{API}/api/public/careers/jobs/{job['job_id']}/lifecycle",
        json={"action": "pause"}, timeout=30,
    )
    r = _apply(job["job_id"], f"phaseA_paused_{int(time.time())}@test.com")
    assert r.status_code == 400
    assert "no longer accepting" in r.json()["detail"].lower() or "paused" in r.json()["detail"].lower()


def test_duplicate_job_creates_draft_with_new_code():
    """Spec §55: duplicated job gets a fresh draft with distinct job_code."""
    job = _make_job()
    r = requests.post(
        f"{API}/api/public/careers/jobs/{job['job_id']}/duplicate",
        json={"admin_id": "pytest"}, timeout=30,
    )
    assert r.status_code == 200
    dup = r.json()["job"]
    assert dup["job_status"] == "draft"
    assert dup["job_code"] != job["job_code"]
    assert dup["slug"] != job["slug"]
    assert dup["title"].endswith("(Copy)")


def test_recruitment_source_persisted():
    """Spec §44 source tracking flows through apply → list."""
    job = _make_job()
    email = f"phaseA_src_{int(time.time())}@test.com"
    app_id = _apply(job["job_id"], email, source="WhatsApp").json()["application_id"]
    rl = requests.get(f"{API}/api/public/careers/applications", timeout=30).json()
    app = next(a for a in rl["applications"] if a["application_id"] == app_id)
    assert app["recruitment_source"] == "WhatsApp"


def test_auto_close_when_vacancies_filled():
    """Spec §55 auto_close_when_filled + §56 vacancy tracking."""
    job = _make_job(vacancy_count=1, auto_close_when_filled=True)
    email = f"phaseA_close_{int(time.time())}@test.com"
    app_id = _apply(job["job_id"], email).json()["application_id"]
    # Drive the applicant through to `joined`
    for status in ["shortlisted", "selected", "joined"]:
        r = requests.put(
            f"{API}/api/public/careers/applications/{app_id}/status",
            json={"status": status, "admin_id": "pytest"}, timeout=30,
        )
        assert r.status_code == 200
    # Job should be closed automatically
    detail = requests.get(f"{API}/api/public/careers/jobs/{job['job_id']}", timeout=30).json()["job"]
    assert detail["job_status"] == "closed"
    # New applications now blocked
    r = _apply(job["job_id"], f"phaseA_after_close_{int(time.time())}@test.com")
    assert r.status_code == 400
